// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpexTech.Data;

#nullable disable

namespace UpexTech.Data.Migrations
{
    [DbContext(typeof(UpexTechDbContext))]
    [Migration("20251222123936_InitialSQLite")]
    partial class InitialSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("UpexTech.Entity.AccountTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountTransactions");
                });

            modelBuilder.Entity("UpexTech.Entity.Banner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("UpexTech.Entity.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 566, DateTimeKind.Local).AddTicks(9309),
                            IsActive = true,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 566, DateTimeKind.Local).AddTicks(9315),
                            IsActive = true,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 566, DateTimeKind.Local).AddTicks(9318),
                            IsActive = true,
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 566, DateTimeKind.Local).AddTicks(9320),
                            IsActive = true,
                            Name = "Huawei"
                        });
                });

            modelBuilder.Entity("UpexTech.Entity.BrowsingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("BrowsingHistories");
                });

            modelBuilder.Entity("UpexTech.Entity.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("UpexTech.Entity.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("UpexTech.Entity.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 566, DateTimeKind.Local).AddTicks(8043),
                            DisplayOrder = 1,
                            Icon = "bi-phone",
                            IsActive = true,
                            Name = "Akıllı Telefonlar"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 566, DateTimeKind.Local).AddTicks(8050),
                            DisplayOrder = 2,
                            Icon = "bi-tablet",
                            IsActive = true,
                            Name = "Tabletler"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 566, DateTimeKind.Local).AddTicks(8053),
                            DisplayOrder = 3,
                            Icon = "bi-headphones",
                            IsActive = true,
                            Name = "Aksesuarlar"
                        });
                });

            modelBuilder.Entity("UpexTech.Entity.CustomerGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CustomerGroups");
                });

            modelBuilder.Entity("UpexTech.Entity.CustomerGroupPriceList", b =>
                {
                    b.Property<int>("CustomerGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PriceListId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("CustomerGroupId", "PriceListId");

                    b.HasIndex("PriceListId");

                    b.ToTable("CustomerGroupPriceLists");
                });

            modelBuilder.Entity("UpexTech.Entity.DeviceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("DeviceModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7508),
                            DisplayOrder = 1,
                            IsActive = true,
                            Level = 0,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7517),
                            DisplayOrder = 1,
                            IsActive = true,
                            Level = 1,
                            Name = "iPhone 15 Serisi",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7537),
                            DisplayOrder = 2,
                            IsActive = true,
                            Level = 1,
                            Name = "iPhone 14 Serisi",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7540),
                            DisplayOrder = 3,
                            IsActive = true,
                            Level = 1,
                            Name = "iPhone 13 Serisi",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7542),
                            DisplayOrder = 4,
                            IsActive = true,
                            Level = 1,
                            Name = "iPhone 12 Serisi",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7544),
                            DisplayOrder = 5,
                            IsActive = true,
                            Level = 1,
                            Name = "iPhone 11 Serisi",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7546),
                            DisplayOrder = 1,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 15",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7548),
                            DisplayOrder = 2,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 15 Plus",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7551),
                            DisplayOrder = 3,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 15 Pro",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7553),
                            DisplayOrder = 4,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 15 Pro Max",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7555),
                            DisplayOrder = 1,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 14",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7557),
                            DisplayOrder = 2,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 14 Plus",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7559),
                            DisplayOrder = 3,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 14 Pro",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7572),
                            DisplayOrder = 4,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 14 Pro Max",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7574),
                            DisplayOrder = 1,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 13",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7576),
                            DisplayOrder = 2,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 13 Mini",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7578),
                            DisplayOrder = 3,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 13 Pro",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7580),
                            DisplayOrder = 4,
                            IsActive = true,
                            Level = 2,
                            Name = "iPhone 13 Pro Max",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7582),
                            DisplayOrder = 2,
                            IsActive = true,
                            Level = 0,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7584),
                            DisplayOrder = 1,
                            IsActive = true,
                            Level = 1,
                            Name = "Galaxy S24 Serisi",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7586),
                            DisplayOrder = 2,
                            IsActive = true,
                            Level = 1,
                            Name = "Galaxy S23 Serisi",
                            ParentId = 19
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7588),
                            DisplayOrder = 1,
                            IsActive = true,
                            Level = 2,
                            Name = "Galaxy S24",
                            ParentId = 20
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7590),
                            DisplayOrder = 2,
                            IsActive = true,
                            Level = 2,
                            Name = "Galaxy S24+",
                            ParentId = 20
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7592),
                            DisplayOrder = 3,
                            IsActive = true,
                            Level = 2,
                            Name = "Galaxy S24 Ultra",
                            ParentId = 20
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7594),
                            DisplayOrder = 1,
                            IsActive = true,
                            Level = 2,
                            Name = "Galaxy S23",
                            ParentId = 21
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7596),
                            DisplayOrder = 2,
                            IsActive = true,
                            Level = 2,
                            Name = "Galaxy S23+",
                            ParentId = 21
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(7598),
                            DisplayOrder = 3,
                            IsActive = true,
                            Level = 2,
                            Name = "Galaxy S23 Ultra",
                            ParentId = 21
                        });
                });

            modelBuilder.Entity("UpexTech.Entity.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("UpexTech.Entity.FavoriteCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("FavoriteCollections");
                });

            modelBuilder.Entity("UpexTech.Entity.FavoriteCollectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CollectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FavoriteId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FavoriteId");

                    b.HasIndex("CollectionId", "FavoriteId")
                        .IsUnique();

                    b.ToTable("FavoriteCollectionItems");
                });

            modelBuilder.Entity("UpexTech.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("UpexTech.Entity.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("UpexTech.Entity.PriceList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BasePriceListId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rounding")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BasePriceListId");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("UpexTech.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriticalStockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsImmediateDelivery")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceB2B")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceB2C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnicalSpecs")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(5139),
                            CriticalStockLevel = 10,
                            Description = "A19 Pro çip, ProMotion ekran, Titanyum tasarım",
                            Image = "iphone-17.webp",
                            IsActive = true,
                            IsImmediateDelivery = false,
                            IsPopular = true,
                            Name = "Apple iPhone 17 256GB",
                            PriceB2B = 81000m,
                            PriceB2C = 89999m,
                            PurchasePrice = 72000m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 325,
                            SKU = "APL-IP17-256",
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(5152),
                            CriticalStockLevel = 10,
                            Description = "Ultra ince tasarım, M3 çip, 48MP kamera",
                            Image = "iphone-air.webp",
                            IsActive = true,
                            IsImmediateDelivery = false,
                            IsPopular = true,
                            Name = "Apple iPhone Air 128GB",
                            PriceB2B = 67500m,
                            PriceB2C = 74999m,
                            PurchasePrice = 60000m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 280,
                            SKU = "APL-IPAIR-128",
                            Stock = 40
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(5157),
                            CriticalStockLevel = 10,
                            Description = "Snapdragon 8 Gen 4, 200MP kamera, S Pen dahil",
                            Image = "galaxy-s25-ultra.png",
                            IsActive = true,
                            IsImmediateDelivery = false,
                            IsPopular = true,
                            Name = "Samsung Galaxy S25 Ultra 512GB",
                            PriceB2B = 76500m,
                            PriceB2C = 84999m,
                            PurchasePrice = 68000m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 410,
                            SKU = "SMS-GS25U-512",
                            Stock = 60
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(5161),
                            CriticalStockLevel = 10,
                            Description = "Galaxy AI, 50MP kamera, Dynamic AMOLED 2X",
                            Image = "galaxy-s25.png",
                            IsActive = true,
                            IsImmediateDelivery = false,
                            IsPopular = true,
                            Name = "Samsung Galaxy S25 256GB",
                            PriceB2B = 49500m,
                            PriceB2C = 54999m,
                            PurchasePrice = 44000m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 290,
                            SKU = "SMS-GS25-256",
                            Stock = 55
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(5411),
                            CriticalStockLevel = 10,
                            Description = "Leica kamera, Snapdragon 8 Elite, 120W hızlı şarj",
                            Image = "Xiaomi-15-pro.webp",
                            IsActive = true,
                            IsImmediateDelivery = true,
                            IsPopular = false,
                            Name = "Xiaomi 15 Pro 512GB",
                            PriceB2B = 40500m,
                            PriceB2C = 44999m,
                            PurchasePrice = 36000m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 195,
                            SKU = "XMI-15P-512",
                            Stock = 45
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 567, DateTimeKind.Local).AddTicks(5421),
                            CriticalStockLevel = 10,
                            Description = "Leica optik, LTPO AMOLED, 5000mAh batarya",
                            Image = "Xiaomi-15.webp",
                            IsActive = true,
                            IsImmediateDelivery = true,
                            IsPopular = false,
                            Name = "Xiaomi 15 256GB",
                            PriceB2B = 31500m,
                            PriceB2C = 34999m,
                            PurchasePrice = 28000m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 180,
                            SKU = "XMI-15-256",
                            Stock = 35
                        });
                });

            modelBuilder.Entity("UpexTech.Entity.ProductDeviceModel", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId", "DeviceModelId");

                    b.HasIndex("DeviceModelId");

                    b.ToTable("ProductDeviceModels");
                });

            modelBuilder.Entity("UpexTech.Entity.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AltText")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("UpexTech.Entity.ProductVariation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PriceAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VariationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VariationValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariations");
                });

            modelBuilder.Entity("UpexTech.Entity.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuoteNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("UpexTech.Entity.QuoteItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuoteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteItems");
                });

            modelBuilder.Entity("UpexTech.Entity.Return", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReturnNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ReturnNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("UpexTech.Entity.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("UpexTech.Entity.SavedCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryMonth")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiryYear")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SavedCards");
                });

            modelBuilder.Entity("UpexTech.Entity.StockAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductVariationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariationId");

                    b.HasIndex("UserId");

                    b.ToTable("StockAlerts");
                });

            modelBuilder.Entity("UpexTech.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriceListId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceListName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxDocument")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 22, 15, 39, 35, 565, DateTimeKind.Local).AddTicks(8537),
                            Email = "admin@upextech.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "admin123",
                            Role = 1,
                            Status = 2,
                            Tier = 1
                        });
                });

            modelBuilder.Entity("UpexTech.Entity.AccountTransaction", b =>
                {
                    b.HasOne("UpexTech.Entity.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.Brand", b =>
                {
                    b.HasOne("UpexTech.Entity.Category", "Category")
                        .WithMany("Brands")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UpexTech.Entity.BrowsingHistory", b =>
                {
                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.Cart", b =>
                {
                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithOne()
                        .HasForeignKey("UpexTech.Entity.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.CartItem", b =>
                {
                    b.HasOne("UpexTech.Entity.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UpexTech.Entity.CustomerGroupPriceList", b =>
                {
                    b.HasOne("UpexTech.Entity.CustomerGroup", "CustomerGroup")
                        .WithMany("PriceLists")
                        .HasForeignKey("CustomerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.PriceList", "PriceList")
                        .WithMany("CustomerGroups")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerGroup");

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("UpexTech.Entity.DeviceModel", b =>
                {
                    b.HasOne("UpexTech.Entity.DeviceModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("UpexTech.Entity.Favorite", b =>
                {
                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.FavoriteCollection", b =>
                {
                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.User", null)
                        .WithMany("FavoriteCollections")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.FavoriteCollectionItem", b =>
                {
                    b.HasOne("UpexTech.Entity.FavoriteCollection", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.Favorite", "Favorite")
                        .WithMany("CollectionItems")
                        .HasForeignKey("FavoriteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Favorite");
                });

            modelBuilder.Entity("UpexTech.Entity.Order", b =>
                {
                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.OrderItem", b =>
                {
                    b.HasOne("UpexTech.Entity.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UpexTech.Entity.PriceList", b =>
                {
                    b.HasOne("UpexTech.Entity.PriceList", "BasePriceList")
                        .WithMany()
                        .HasForeignKey("BasePriceListId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BasePriceList");
                });

            modelBuilder.Entity("UpexTech.Entity.Product", b =>
                {
                    b.HasOne("UpexTech.Entity.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UpexTech.Entity.ProductDeviceModel", b =>
                {
                    b.HasOne("UpexTech.Entity.DeviceModel", "DeviceModel")
                        .WithMany("Products")
                        .HasForeignKey("DeviceModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany("CompatibleModels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceModel");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UpexTech.Entity.ProductImage", b =>
                {
                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UpexTech.Entity.ProductVariation", b =>
                {
                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany("Variations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UpexTech.Entity.Quote", b =>
                {
                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.QuoteItem", b =>
                {
                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.Quote", "Quote")
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("UpexTech.Entity.Return", b =>
                {
                    b.HasOne("UpexTech.Entity.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.Review", b =>
                {
                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.SavedCard", b =>
                {
                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.StockAlert", b =>
                {
                    b.HasOne("UpexTech.Entity.Product", "Product")
                        .WithMany("StockAlerts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UpexTech.Entity.ProductVariation", "ProductVariation")
                        .WithMany()
                        .HasForeignKey("ProductVariationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("UpexTech.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("ProductVariation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpexTech.Entity.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("UpexTech.Entity.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UpexTech.Entity.Category", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("UpexTech.Entity.CustomerGroup", b =>
                {
                    b.Navigation("PriceLists");
                });

            modelBuilder.Entity("UpexTech.Entity.DeviceModel", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("UpexTech.Entity.Favorite", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("UpexTech.Entity.FavoriteCollection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UpexTech.Entity.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("UpexTech.Entity.PriceList", b =>
                {
                    b.Navigation("CustomerGroups");
                });

            modelBuilder.Entity("UpexTech.Entity.Product", b =>
                {
                    b.Navigation("CompatibleModels");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("StockAlerts");

                    b.Navigation("Variations");
                });

            modelBuilder.Entity("UpexTech.Entity.Quote", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UpexTech.Entity.User", b =>
                {
                    b.Navigation("FavoriteCollections");

                    b.Navigation("Favorites");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
